### ISSUE TITLE
BLE downlink not working

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie2-nrf-firmware#10]
The BLE downlink is not working properly. It is only working if a Crazyradio is connected at the same time as BLE. When the Crazyradio disconnects the downlink stops even though the STM32 continues to send log packets.

**Comment by ataffanel** [comment]
Related to bitcraze/crazyflie-firmware#81

**Comment by glennvdw** [comment]
Any updates on what might be causing the issue?

**Comment by ataffanel** [comment]
Sending back BLE packet was in the wrong "if", it was not sendig packet back if the ESB (Crazyradio) queue was full. This is now fixed and I tested it by:
 - Connecting with the iPhone app
 - Connecting with the Client, the iphone app see downlink packets
 - Disconnecting the client, the downlink packets continues to come (it is the log block setup by the client)

**Comment by glennvdw** [comment]
It works!

Thank you :D
