### ISSUE TITLE
Link to s110 zip is broken

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie2-nrf-firmware#26]
The link used in the script tools/build/download_deps to download the S110 softdevice is broken. We need to find a new link for it and update the script.

See forum for initial report: https://forum.bitcraze.io/viewtopic.php?f=5&t=3258

**Comment by yl5006** [comment]
hi @ataffanel 
what is the Bluetooth LE  address？

**Comment by ataffanel** [comment]
@yl5006 can you please ask your question on a new issue or on the Bitcraze forum (https://forum.bitcraze.io), this issue is used to track development and is not the right forum for random questions.

**Comment by NicksonYap** [comment]
@ataffanel  anyway I can get the files?
Only v8 seems to be downloadable

Perhaps I can copy from here?
https://github.com/Seeed-Studio/mbed_ble/tree/master/mbed-src/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/Lib/s110_nrf51822_7_0_0/s110_nrf51822_7.0.0_API

**Comment by NicksonYap** [comment]
I think it's best that the repo hosts the file, this is to avoid breaking this repo
Are there any legal reasons it cannot be included in the repo?

**Comment by NicksonYap** [comment]
Here you go:

[s110_nrf51822_7.0.0.zip](https://github.com/bitcraze/crazyflie2-nrf-firmware/files/2686388/s110_nrf51822_7.0.0.zip)

(recovered from: https://github.com/Seeed-Studio/mbed_ble/tree/master/mbed-src/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/Lib/s110_nrf51822_7_0_0)

**Comment by ataffanel** [comment]
@NicksonYap Thanks a lot, we actually got a link from NordicSemi. I am updating the scripts with the new Nordic link.

@JGSuw This is interesting, thanks for noticing the files in the sdk! Now that we have the s110 link up again it also allows people to reflash the softdevice so updating the link is still good. Though if it breaks again in the future it is good to know that the sdk also has the header files.
