### ISSUE TITLE
ble.c file will not compile 

### ISSUE THREAD

**Issue by ruvmark** [bitcraze/crazyflie2-nrf-firmware#4]
I downloaded the vm, when i open up eclipse my ble.c file will not compile. There is many constants that it says are not findable, for example the uin32_t and others. Not sure whats going on..

**Comment by ataffanel** [comment]
the script tools/build/download_deps.sh has been added to the repos and will fetch all required code from Nordic to build the bluetooth.

Tested to work on the virtual machine (on the VM curl needs to be installed first with ```sudo apt-get install curl```).
