### ISSUE TITLE
Charging state is not updated correctly if there is no charger chip

### ISSUE THREAD

**Issue by tobbeanton** [bitcraze/crazyflie2-nrf-firmware#61]
See original issue [#819 in crazyflie-firmware](https://github.com/bitcraze/crazyflie-firmware/issues/819) for details.

**Comment by ntamas** [comment]
Would this mean that `pmUSBPower()` will return `false` if there is no charger chip even if I plug in a USB cable and power the drone from that (for development purposes)?
