### ISSUE TITLE
Crazyflie doesn't boot with 2024.2

### ISSUE THREAD

**Issue by williamleong** [bitcraze/crazyflie2-nrf-firmware#95]
I'm facing an issue where after flashing 2024.2, the Crazyflie only shows a solid blue light at M2 and doesn't do anything else upon power on. However, reverting to 2023.11 works.

**Comment by ataffanel** [comment]
What version of the client/lib are you using? Flashing 2024.2 requires the latest version of the client and of the lib. Flashing with the client 2024.2 should work.

**Comment by williamleong** [comment]
Thanks, that must be it, I'm on an older version.
